export default [
    {
        //1  Low
        //2 Medium
        //3 High
        Title:"Task1",
        priority:1,
        Date:"11/02/2024",
        operation:"Active"
    },
    {
        Title:"Task2",
        priority:2,
        Date:"13/02/2024",
        operation:"Active"
    },
    {
        Title:"Task3",
        priority:3,
        Date:"15/02/2024",
        operation:"Active"
    },
    {
        Title:"Task4",
        priority:1,
        Date:"16/02/2024",
        operation:"Active"
    },
    {
        Title:"Task5",
        priority:3,
        Date:"17/02/2024",
        operation:"Deactive"
    },
    {
        Title:"Task6",
        priority:1,
        Date:"11/02/2024",
        operation:"Deactive"
    }
    ,
    {
        Title:"Task7",
        priority:2,
        Date:"12/02/2024",
        operation:"Deactive"
    },
    {
        Title:"Task8",
        priority:3,
        Date:"13/02/2024",
        operation:"Deactive"
    },
    {
        Title:"Task9",
        priority:1,
        Date:"14/02/2024",
        operation:"Deactive"
    },
    {
        Title:"Task10",
        priority:2,
        Date:"15/02/2024",
        operation:"Active"
    },
    {
        Title:"Task11",
        priority:2,
        Date:"16/02/2024",
        operation:"Deactive"
    },
    {
        Title:"Task12",
        priority:3,
        Date:"16/02/2024",
        operation:"Active"
    }
];